name: 🙂 Feature request
description: Request a new feature
title: "[Request]: "
labels: ["request", "triage"]
assignees:
  - HernandoMV
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request for a new functionality!
        Please fill out the sections below
  - type: input
    id: requestor
    attributes:
      label: Requestor
      description: Who wants this request to be implemented?
      placeholder: Yamuna
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: Briefly describe the request
      placeholder: i want more free time
    validations:
      required: true
  - type: input
    id: justification
    attributes:
      label: Business Justification
      description: Justify why this request should be implemented
      placeholder: to make Esya a better place
    validations:
      required: true
  - type: input
    id: solution
    attributes:
      label: Proposed solution
      description: How should this be done?
      placeholder: by coding, obviously
    validations:
      required: true
  - type: dropdown
    id: tier
    attributes:
      label: Impacted Software Tier
      description: Tier affected
      options:
        - Tier 1
        - Tier 2
        - Tier 3
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: Estimated time
      description: Estimate the time required to implement this request
      placeholder: 3 hours
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: What do you want?
      description: If you want to expand on what ideas you have, please do so here
      placeholder: Make my wishes true...
      value: "I want new stuff!"
    validations:
      required: false
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How fast would you like this to be implemented?
      options:
        - Not urgent
        - It would be nice to have it soon
        - Yesterday!
    validations:
      required: false