name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - HernandoMV
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please fill out the sections below
  - type: input
    id: requestor
    attributes:
      label: Requestor
      description: Who wants this bug to be fixed?
      placeholder: Yamuna
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: Briefly describe the bug
      placeholder: it is a nasty creature
    validations:
      required: true
  - type: input
    id: justification
    attributes:
      label: Business Justification
      description: Justify why this bug should be fixed
      placeholder: to make Esya a better place
    validations:
      required: true
  - type: input
    id: solution
    attributes:
      label: Proposed solution
      description: How should this be fixed?
      placeholder: by coding, obviously
    validations:
      required: false
  - type: dropdown
    id: tier
    attributes:
      label: Impacted Software Tier
      description: Tier affected
      options:
        - Tier 1
        - Tier 2
        - Tier 3
    validations:
      required: false
  - type: input
    id: time
    attributes:
      label: Estimated time
      description: Estimate the time required to fix this bug
      placeholder: 3 hours
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: What happened?
      description: If you want to expand on what happened, please do so here
      placeholder: Everything was working fine, then... caos!!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How fast would you like this to be solved?
      options:
        - Not urgent
        - It would be nice to have it soon
        - Yesterday!
    validations:
      required: false